config/routes.rb
Rails.application.routes.draw do



  # admins
  devise_for :admins
  resources :admins, only: [:show]

  as :admin do
    get 'admins', :to => 'admins#show', :as => :admin_root
  end

  # apps
  resources :apps do
    resources :events, only: [:show]
    member do
      get 'users'
      get 'events'
      get 'settings'
    end
  end


  # api
  namespace :api, defaults: { format: :json } do
    namespace :v1 do
      match '/events', to: 'events#preflight', via: [:options]
      resources :events, only: [:create]
    end
  end


  root 'welcome#index'

end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  validates :name, presence: true

  has_many :apps

end

app/models/app.rb
class App < ApplicationRecord

  belongs_to :admin
  has_many :users, dependent: :destroy
  has_many :events, dependent: :destroy

  validates :name, presence: true
  validates :url,  presence: true

  after_create  :generate_app_id

  default_scope { order('name ASC') }

  def generate_app_id
    loop do
      id_code = ("a".."z").to_a.sample + SecureRandom.uuid[0,5]
      return update_attribute(:id_code, id_code) unless App.exists?(id_code: id_code)
    end
  end


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :app
  belongs_to :user

  validates :app, presence: true
  validates :name, presence: true

  default_scope { order('created_at DESC') }

end

app/models/user.rb
class User < ApplicationRecord

  validates :app, presence: true
  validates :email, presence: true

  after_create :update_last_seen_at

  belongs_to :app
  has_many :events, dependent: :destroy

  default_scope { order('last_seen_at DESC') }

  def update_name(name)
    update_attribute(:name, name)
  end

  def update_last_seen_at
    update_attribute(:last_seen_at, Time.now)
  end

  def update_web_sessions
    increment(:web_sessions) if Time.now > self.last_seen_at + 30.minutes || self.web_sessions == 0
  end

end

app/controllers/admins_controller.rb
class AdminsController < ApplicationController
  def show
  end
end

app/controllers/api/v1/base_controller.rb
class Api::V1::BaseController < ApplicationController

  skip_before_action :verify_authenticity_token
  skip_before_action :authenticate_admin!

  rescue_from ActionController::ParameterMissing, with: :malformed_request
  rescue_from ActiveRecord::RecordNotFound, with: :not_found

  def malformed_request
    render json: { error: "The request could not be understood by the server due to malformed syntax. The client SHOULD NOT repeat the request without modifications", status: 400 }, status: 400
  end

  def not_found
    render json: { error: "Record not found", status: 404 }, status: 404
  end

end

app/controllers/api/v1/events_controller.rb
class Api::V1::EventsController < Api::V1::BaseController

  before_filter :set_access_control_headers


  def preflight
    head 200
  end


  def set_access_control_headers
    # set CORS headers so controller actions will allow POST requests from other domains
    headers['Access-Control-Allow-Origin'] = '*'
    headers['Access-Control-Allow-Methods'] = 'POST, GET, OPTIONS'
    headers['Access-Control-Allow-Headers'] = 'Content-Type'
  end


  def create
    @app = App.find_by(id_code: params[:app_id])
    if @app # TODO && request.env['HTTP_ORIGIN'] == @app.url
      @user = find_or_create_user
      if @user
        # ASSOCIATE EVENT WITH USER AND APP
        @event = @user.events.build(event_params)
        @event.app = @app
        save_event
      else
        # ASSOCIATE EVENT WITH APP ONLY
        @event = @app.events.build(event_params)
        save_event
      end
    else
      render json: "Unknown application", status: :unprocessable_entity
    end
  end


  def find_or_create_user
    if params[:user] && params[:user][:email]
      user = User.find_or_create_by!(app: @app, email: params[:user][:email])
      user.update_name(params[:user][:name])
      user.update_web_sessions
      user.update_last_seen_at
    else
      user = nil
    end
    user
  end


  def save_event
    if @event.save
      render json: @event, status: :created
    else
      render json: { errors: @event.errors.messages }, status: :unprocessable_entity
    end
  end


  private
  def event_params
    params.require(:event).permit(:name)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :authenticate_admin!

  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(admin)
    admin_path(admin)
  end

  protected
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
    devise_parameter_sanitizer.permit(:account_update, keys: [:name])
  end
end

app/controllers/apps_controller.rb
class AppsController < ApplicationController


  def index
    @apps = App.all
  end


  def show
    @app = App.find(params[:id])
    @events = @app.events.group_by(&:name)
    @pie_chart_data = @app.events.group_by(&:name).map { |k,v| {name: k, y: v.count} }.to_json
  end


  def new
    @app = App.new
  end


  def create
    @app = current_admin.apps.new(app_params)
    if @app.save
      flash.now[:notice] = "App successfully created!"
      redirect_to app_path(@app)
    else
      flash.now[:alert] = "App could not be saved!"
      render :new
    end
  end


  def users
    @app = App.find(params[:id])
  end


  def events
    @app = App.find(params[:id])
  end


  def settings
    @app = App.find(params[:id])
  end


  def update
    @app = App.find(params[:id])
    @app.assign_attributes(app_params)
    if @app.save
      flash.now[:notice] = "Changes saved!"
      redirect_to app_path(@app)
    else
      flash.now[:alert] = "App could not be updated!"
    end
  end


  def destroy
    @app = App.find(params[:id])
    if @app.destroy
      flash.now[:notice] = "App deleted!"
      redirect_to admin_root_path
    else
      flash.now[:alert] = "App could not be deleted!"
      redirect_to settings_app_path(@app)
    end
  end


  private

  def app_params
    params.require(:app).permit(:name, :url)
  end

end

app/controllers/events_controller.rb
class EventsController < ApplicationController

  def show
    @event        = Event.find(params[:id])
    @app          = App.find(params[:app_id])
    @events       = @app.events.where(name: @event.name).sort_by { |e| e.created_at}
    @chart_data   = @events.group_by {|e| e.created_at.to_date}.map { |k,v| [k.to_datetime.to_i * 1000, v.count]}.to_json
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  skip_before_action :authenticate_admin!

  def index
  end

end

app/helpers/admins_helper.rb
module AdminsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper

  def form_group_tag(errors, &block)
    css_class = 'form-group'
    css_class << ' form-has-error' if errors.any?
    content_tag :div, capture(&block), class: css_class
  end

end

app/helpers/apps_helper.rb
module AppsHelper


  def app_nav_item_div(current_page, title)
    if current_page
      output = "<div class='app-nav-item app-nav-item-active'>"
    else
      output = "<div class='app-nav-item'>"
    end
    output += title
    output += "</div>"
    output.html_safe
  end


  def if_recent_span(datetime)
    if datetime > 30.minutes.ago
      output = "<span class='recent'>"
    else
      output = "<span>"
    end
    output += distance_of_time_in_words(datetime, Time.now )
    output += " ago"
    output += "</span>"
    output.html_safe
  end


end

app/helpers/devise_helper.rb
module DeviseHelper

  def devise_error_messages!
    resource.errors
  end

end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/admins/show.html.erb
<div class="apps-header">
  <div class="apps-body">
    My Apps <%= "(#{current_admin.apps.count})" %>
    <%= link_to "New", new_app_path, id: 'new-app-button'%>
  </div>
</div>
<br>
<%= render current_admin.apps %>

app/views/apps/_app.html.erb
<%= link_to app_path(app) do %>
    <div class="list-group">
      <div id="app-<%= app.id %>" class="app-list">
        <i class="ion-cube app"></i>
        <div class="app-name">
          <%= app.name %>
        </div>
        <div class="app-url">
          <%= app.url %>
        </div>
      </div>
    </div>
<% end %>

app/views/apps/_app_header.html.erb
<div class="app-header">
  <div class="app-body">
    <%= link_to admin_root_path, class: 'my-apps-link' do %>
        My Apps
    <% end %>
    <i id="icon-right-chevron" class="ion-chevron-right"></i>
    <i class="ion-cube app-icon"></i>
    <%= @app.name %>
  </div>
</div>

app/views/apps/_app_subnav.html.erb
<div class="app-show-nav">

  <!-- APP OVERVIEW -->
  <%= link_to app_path(@app) do %>
      <%= app_nav_item_div((params[:controller] == 'apps' && params[:action] == 'show') , 'Overview') %>
  <% end %>

  <!-- APP USERS -->
  <%= link_to users_app_path(@app) do %>
    <%= app_nav_item_div((params[:controller] == 'apps' && params[:action] == 'users') , 'Users') %>
  <% end %>

  <!-- APP EVENTS -->
  <%= link_to events_app_path(@app) do %>
    <%= app_nav_item_div((params[:controller] == 'apps' && params[:action] == 'events') , 'Events') %>
  <% end %>

  <!-- APP SETTINGS -->
  <%= link_to settings_app_path(@app) do %>
      <%= app_nav_item_div((params[:controller] == 'apps' && params[:action] == 'settings') , 'Settings') %>
  <% end %>

</div>

app/views/apps/_form.html.erb
<div class="app-form">

    <%= form_for app do |f| %>
        <div class="app-form-group">
          <div class="app-form-group-label col-sm-3 ">
            <p>App Name</p>
          </div>
          <div class="app-form-group-input-section col-sm-9 ">
            <%= f.text_field :name, class: 'app-form-input form-control', placeholder: "App name" %>
            <small class="error-message"><%= app.errors.messages[:name].first %></small>
          </div>
        </div>

        <div class="app-form-group">
          <div class="app-form-group-label col-sm-3 ">
            <p>App URL</p>
          </div>
          <div class="app-form-group-input-section col-sm-9 ">
            <%= f.text_field :url, class: 'app-form-input form-control', placeholder: "App URL" %>
            <small class="error-message"><%= app.errors.messages[:url].first %></small>
          </div>
        </div>

        <div>
          <div class="col-sm-3"></div>
          <div id="new-app-button" class="col-sm-9">
            <%= f.submit app.new_record? ? 'Create App' : 'Save Changes' %>
          </div>
        </div>
    <% end %>

</div>

app/views/apps/events.html.erb
<%= render partial: 'apps/app_header' %>
<%= render partial: 'apps/app_subnav' %>

<div class="app-lists">
  <% if @app.events.any? %>
      <table class="table">
        <thead>
        <tr>
          <th>EVENT</th>
          <th class="">OCCURRED</th>
          <th class="app-lists-column-collapse">USER</th>
        </tr>
        </thead>
        <tbody>
        <% @app.events.each do |event| %>
            <tr>
              <td><%= link_to event.name, app_event_path(event.app, event) %></td>
              <td><%= if_recent_span(event.created_at) %></td>
              <td class="app-lists-column-collapse"><%= event.user ? event.user.name : "Anonymous" %></td>
            </tr>
        <% end %>
        </tbody>
      </table>
  <% else %>
    <h2>0 Events found</h2>
  <% end %>
</div>

app/views/apps/new.html.erb
<div class="apps-header">
  <div class="apps-body">
    <div class="apps-body-title">
      New app
    </div>
  </div>
</div>
<%= render partial: 'form', locals: { app: @app } %>

app/views/apps/settings.erb
<%= render partial: 'apps/app_header' %>
<%= render partial: 'apps/app_subnav' %>
<%= render partial: 'form', locals: { app: @app } %>

<!-- DELETE APP BUTTON -->
<div class="delete-app-form">
  <div class="app-form-group">
    <div class="app-form-group-label col-sm-3"></div>
      <div id="delete-app-button" class="app-form-group-input-section col-sm-9">
        <%= button_to 'Delete App', @app, class: 'app-form-input', method: :delete, data: { confirm: 'Are you sure?', disable_with: 'Deleting...' } %>
      </div>
  </div>
</div>

app/views/apps/show.html.erb
<%= render partial: 'apps/app_header' %>
<%= render partial: 'apps/app_subnav' %>
<div class="app-details">
  <h3><%= @app.name %>: <%= link_to @app.url, @app.url %></h3>
  <br>
  <% if @app.events.any? %>
    <div id="events-pie-chart" class="pie-chart"></div>
    <br>
  <% end %>
  <br>
  <div class="installation">
    <h4>Installation</h4>
    <pre>
      &lt;script&gt;
      window.analyticsSettings = {
        app_id: "<%= @app.id_code %>",             // your app_id (required)
        name: "Example User",         // current user name (optional)
        email: "user@example.com"     // current user email (optional)
      };
      &lt;/script&gt;
      &lt;script src="http://analytics.jasonlukeball.com/analytics.js">&lt;/script&gt;
    </pre>
    <br>
    <h4>Event Tracking</h4>
    <pre>
      analytics.track('created-todo');
    </pre>
  </div>
</div>

<% content_for :extended_scripts do %>
    <script type="text/javascript">
        $(document).ready(function(){
            // PIE CHART
            $(function () {
                Highcharts.theme = {
                    colors: ["#7761A8", LightenDarken("#7761A8", 30), LightenDarken("#7761A8", 60), LightenDarken("#7761A8", 90), LightenDarken("#7761A8", 120), LightenDarken("#7761A8", 30), LightenDarken("#7761A8", 60), LightenDarken("#7761A8", 90), LightenDarken("#7761A8", 120)]
                };

                Highcharts.setOptions(Highcharts.theme);    // Apply the theme

                $('#events-pie-chart').highcharts({
                    chart: {
                        plotBackgroundColor: null,
                        plotBorderWidth: null,
                        plotShadow: false,
                        type: 'pie'
                    },

                    title: {
                        text: 'Events'
                    },
                    tooltip: {
                        pointFormat: '<b>{point.y}</b>'
                    },
                    plotOptions: {
                        pie: {
                            allowPointSelect: true,
                            cursor: 'pointer',
                            dataLabels: {
                                enabled: true,
                                format: '<b>{point.name}</b>: {point.y}',
                                style: {
                                    color: (Highcharts.theme && Highcharts.theme.contrastTextColor) || 'black'
                                }
                            }
                        }
                    },
                    series: [{
                        name: 'Events',
                        data: <%= raw(@pie_chart_data) %>
                    }]
                });
            });
        });
    </script>
<% end %>

app/views/apps/users.html.erb
<%= render partial: 'apps/app_header' %>
<%= render partial: 'apps/app_subnav' %>

<div class="app-lists">

  <% if @app.users.any? %>
      <table class="table">
        <thead>
        <tr>
          <th>NAME</th>
          <th>EMAIL</th>
          <th>LAST SEEN</th>
          <th class="app-lists-column-collapse">FIRST SEEN</th>
          <th class="app-lists-column-collapse">SESSIONS</th>
        </tr>
        </thead>
        <tbody>
        <% @app.users.each do |user| %>
          <tr>
            <td><%= user.name %></td>
            <td><%= user.email %></td>
            <td><%= if_recent_span(user.last_seen_at) %></td>
            <td class="app-lists-column-collapse"><%= if_recent_span(user.created_at) %></td>
            <td class="app-lists-column-collapse"><%= user.web_sessions %></td>
          </tr>
      <% end %>
      </tbody>
      </table>
  <% else %>
    <h2>0 Users found</h2>
  <% end %>
</div>

app/views/events/show.html.erb
<%= render partial: 'apps/app_header' %>
<%= render partial: 'apps/app_subnav' %>
<div class="app-details">
  <h3><%= "#{@event.name}: #{pluralize(@events.count, 'Occurrence', 'Occurrences')}" %></h3>
  <br>
</div>

<% content_for :extended_scripts do %>
    <script type="text/javascript">
        $(document).ready(function(){
            // STOCK CHART
            $(function () {
                Highcharts.theme = {
                    colors: ["#BEACD3"],
                    navigator: {
                        handles: {
                            backgroundColor: '#666',
                            borderColor: '#AAA'
                        },
                        outlineColor: '#CCC',
                        maskFill: 'rgba(250, 247, 253, 0.52)',
                        style: {
                            fontFamily: "'Open Sans', sans-serif"
                        },
                        series: {
                            lineColor: '#BEACD3'
                        }
                    }
                };

                Highcharts.setOptions(Highcharts.theme);    // Apply the theme


                // Create the chart
                $('#stock-chart').highcharts('StockChart', {
                    rangeSelector : {
                        selected : 1
                    },

                    title : {
                        text : ''
                    },

                    series : [{
                        name : 'Count',
                        data : <%= raw(@chart_data) %>
                    }]
                });
            });

        });
    </script>

<% end %>


<div id="stock-chart" style="height: 400px; min-width: 310px;"></div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Analytics</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= stylesheet_link_tag    'application', 'https://fonts.googleapis.com/css?family=Open+Sans:400,600,700' %>
  <%= stylesheet_link_tag    'application', 'http://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<!--NAVBAR-->
<nav id="mainNav" class="navbar navbar-default">
  <!--NAVBAR HEADER-->
  <div class="navbar-header">
    <!-- NAVBAR COLLAPSED -->
    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navLinks">
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <!-- /NAVBAR COLLAPSED -->
  </div>

  <!--NAVBAR LINKS-->
  <div class="collapse navbar-collapse" id="navLinks">
    <ul class="nav navbar-nav navbar-right">
      <% if current_admin %>
          <li><%= link_to "My Apps", admin_path(current_admin), :class => 'navbar-link' %></li>
          <li><%= link_to "Edit profile", edit_admin_registration_path, :class => 'navbar-link' %></li>
          <li><%= link_to "Sign Out", destroy_admin_session_path, method: :delete, :class => 'navbar-link'  %></li>
      <% else %>
          <li><%= link_to "Sign Up", new_admin_registration_path, :class => 'navbar-link'  %></li>
          <li><%= link_to "Log In", new_admin_session_path, :class => 'navbar-link'  %></li>
      <% end %>
    </ul>
  </div>
</nav>
<!--/NAVBAR-->



  <!--FLASH MESSAGES-->
  <div class="flash">
    <% if flash[:notice] %>
        <div class="alert alert-success">
          <%= flash[:notice] %>
        </div>
    <% elsif flash.now[:alert] %>
        <div class="alert alert-danger">
          <%= flash.now[:alert] %>
        </div>
    <% elsif flash[:alert] %>
        <div class="alert alert-warning">
          <%= flash[:alert] %>
        </div>
    <% end %>
  </div>
  <!-- /FLASH-MESSAGES -->

  <%= yield %>


  <div class="footer">
  </div>


    <%= yield :extended_scripts %>
</body>
</html>

app/views/welcome/index.html.erb
<div class="welcome-wrapper">
  <br><br>
    <h2>Analytics</h2>
    <h3>A JavaScript API to track users & events in your web apps</h3>
    <br><br>
    <%= image_tag('analytics-demo.gif', id: 'demo-app-gif') %>
    <br>
      <div class="installation">
        <br>
        <h4>Easy Installation</h4>
        <pre>
          &lt;script&gt;
          window.analyticsSettings = {
            app_id: "your_app_id",
            name: "Example User",
            email: "user@example.com"
          };
          &lt;/script&gt;
          &lt;script src="http://analytics.jasonlukeball.com/analytics.js">&lt;/script&gt;
        </pre>
        <br><br>
        <h4>Track user actions in your apps</h4>
        <pre>
          analytics.track('created-todo');
        </pre>
      </div>
</div>